[versions]
activityVersion = "1.12.2"
agp = "8.12.3"
core = "3.5.4"
coreSplashscreen = "1.2.0"
eventbus = "3.3.1"
gson = "2.13.2"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
libphonenumber = "9.0.21"
material = "1.13.0"
activity = "1.8.0"
constraintlayout = "2.2.1"
roomTesting = "2.8.4"
roomCompiler = "2.8.4"
securityCrypto = "1.1.0"
preference = "1.2.1"
zxingAndroidEmbedded = "4.3.0"

[libraries]
activity-v1122 = { module = "androidx.activity:activity", version.ref = "activityVersion" }
core = { module = "com.google.zxing:core", version.ref = "core" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
eventbus = { module = "org.greenrobot:eventbus", version.ref = "eventbus" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
libphonenumber = { module = "com.googlecode.libphonenumber:libphonenumber", version.ref = "libphonenumber" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomCompiler" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomTesting" }
room-testing = { module = "androidx.room:room-testing", version.ref = "roomTesting" }
security-crypto = { module = "androidx.security:security-crypto", version.ref = "securityCrypto" }
preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }
zxing-android-embedded = { module = "com.journeyapps:zxing-android-embedded", version.ref = "zxingAndroidEmbedded" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

